services:
  fossbadge_postgres:
    image: postgres:latest
    restart: always
    container_name: fossbadge_postgres
    hostname: fossbadge_postgres
    volumes:
      - ./o2badge_dev_db:/var/lib/postgresql
    env_file:
      - .env
    networks:
      - fossbadge_backend

  fossbadge_memcached:
    image: memcached:latest
    container_name: fossbadge_memcached
    hostname: fossbadge_memcached
    restart: always
    networks:
      - fossbadge_backend

  fossbadge_redis:
    image: redis:latest
    container_name: fossbadge_redis
    hostname: fossbadge_redis
    restart: always
    networks:
      - fossbadge_backend

  fossbadge_celery:
    build: .
    container_name: fossbadge_celery
    hostname: fossbadge_celery
    restart: always
    env_file: .env
    user: fossbadge
    depends_on:
      - fossbadge_redis
    links:
      - fossbadge_redis:redis
      - fossbadge_postgres:postgres
      - fossbadge_memcached:memcached
    volumes:
      - ./:/home/fossbadge/FossBadge
    networks:
      - fossbadge_backend
    command: "uv run celery -A fossbadge worker -Q celery,pictures -l INFO -B --concurrency=3"

  fossbadge_django:
    build: .
    container_name: fossbadge_django
    hostname: fossbadge_django
    restart: always
    env_file: .env
    user: fossbadge
    volumes:
      - ./ssh:/home/fossbadge/.ssh
      - ./:/home/fossbadge/FossBadge
    depends_on:
      - fossbadge_celery
      - fossbadge_postgres
    links:
      - fossbadge_redis:redis
      - fossbadge_postgres:postgres
      - fossbadge_memcached:memcached
    networks:
      - fossbadge_backend
    extra_hosts:
      - openbadge.localhost:172.17.0.1

    command: "bash start.sh"

  fossbadge_nginx:
    image: nginx
    restart: always
    container_name: fossbadge_nginx
    hostname: fossbadge_nginx
    volumes:
      - ./media:/www/media
      - ./staticfiles:/www/static
      - ./logs:/logs
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - fossbadge_django
    links:
      - fossbadge_django:fossbadge_django
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.fossbadge_nginx.tls=true
      - traefik.http.routers.fossbadge_nginx.rule=Host(`$DOMAIN`)
      - traefik.http.services.fossbadge_nginx.loadbalancer.server.port=80
    #  - traefik.http.routers.fossbadge_nginx.middlewares=crowdsec@file
    networks:
      - frontend
      - fossbadge_backend

  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    hostname: "traefik"
    command:
      - "--log.level=INFO"
      - "--providers.docker=true"
      - "--providers.docker.network=frontend"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.entrypoints-https.address=:443"
      - "--entrypoints.entrypoints-http.address=:80"
      - "--entrypoints.entrypoints-http.http.redirections.entryPoint.to=entrypoints-https"
      - "--entrypoints.entrypoints-http.http.redirections.entryPoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped
    networks:
      - frontend


networks:
  frontend:
    external: true
  fossbadge_backend:

volumes:
  o2badge_dev_db: