[project]
name = "fossbadge"
version = "0.1.0"
description = "Free and open source platform for Open Badge"
authors = [{ name = "JonasFW13", email = "jturbeaux@pm.me" }]
requires-python = ">=3.14"
readme = "README.md"
license = { text = "AGPLv3" }
dependencies = [
    "django>=5.2",
    "pillow (>=10)",
    "django-htmx (>=1)",
    "djangorestframework (>=3.16)",
    "django-pictures (>=1.4.2)",
    "django-cleanup (>=9.0.0)",
    "gunicorn (>=23.0.0)",
    "beautifulsoup4>=4.14.3",
    "psycopg[binary]>=3.3.2",
    "celery[redis]>=5.6.2",
    "pyopenbadges",
    "django-leaflet>=0.33.0",
    "django-solo>=2.5.1",
    "sentry-sdk>=2.54.0",
    "django-cotton>=2.6.2",
]

[dependency-groups]
dev = [
    "ipdb>=0.13.13,<0.14",
    "django-extensions>=4.1,<5",
    "werkzeug>=3.1.3,<4",
    "pytest-django>=4.12.0",
]

[tool.uv]
package = false

[tool.uv.sources]
pyopenbadges = { path = "temp-dependancies/pyopenbadges-0.1.0-py3-none-any.whl" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "fossbadge.settings"
# Ignore the database's volume folder because else it's create errors
addopts = "--ignore=o2badge_dev_db"
